PythonOT/POT

- ot/bregman.py
- change commented prints to python3 compatible syntax
- Correct issue that could cause the sinkhorn algo to stop with u and v containing nan/infinite numbers:
- Assign uprev and vprev before changing u and v.
- Then update u and v.
- Then check if u and v contain nan, but ALSO infinite values.
- if there are issues, then display error (with 2 r, not 3 :p) along with the iteration number (there may have errors at iteration 0)
> update bregman file

- examples/da/plot_otda_semi_supervised.py
- ot/da.py
- test/test_da.py
cf issue #26 
- added an example for semi supervised DA
- correction for semi supervised DA in `.fit`
- added doc on semi supervised DA
> Domain adaptation corrections

- examples/plot_OT_L1_vs_L2.py
> typo in title

- .travis.yml
- .travis/before_install.sh
- Makefile
- requirements.txt
I added new python to the travis build and removed the macosx build that never worked and made all aother build very slow.
> Add Python 3.5 and 3.6 and remove macosx on travis

- examples/plot_otda_mapping_colors_images.py
Fixes #77 
However, we need to regenerate the notebooks too. @rflamary any hints on that ?
> Minor typo fix in examples. Fixes #77

- .github/workflows/main.yml
- .github/workflows/pythonpackage.yml
- README.md
- codecov.yml
- docs/rtd/index.md
- examples/plot_gromov_barycenter.py
- examples/plot_otda_mapping_colors_images.py
+ Cleanup documentation
+ Debug some examples
+ Add codecov token
+ require flake8 on github actions
> [WIP] Cleanup documentation and examples

- ot/da.py
Issue #207
Issue #207 
Tested using code snippet from issue
> Fix to BaseTransport.transform_labels()

- docs/source/quickstart.rst
As recommended in your comment.
Improve the readability of the documentation.
> Fix minor typo take #2

- README.md
- docs/source/readme.rst
- test/test_ot.py
This is a small documentation PR to add the proper reference to the JMLR paper.
> [MRG] ADD JMLR paper to the readme and documentation

- README.md
- docs/source/readme.rst
- test/test_ot.py
> [MRG] Add Mathieu Blondel in acknoledgements

- .github/workflows/build_tests.yml
- ot/lp/emd_wrap.pyx
> [MRG] Fixes issue #239 (deprecated numpy types)

- ot/lp/__init__.py
Correction of a mistake in the documentation of function emd2.
Tested on linux
> [WIP] Docs correction for emd2

- .github/workflows/build_wheels.yml
- .github/workflows/build_wheels_weekly.yml
Debugging the building of the wheels on master push and with "build wheels" is the commit comment.
> [MRG] Debug wheels build

- README.md
> [WIP] Spell correction in README.md

- .github/workflows/build_tests.yml
- Makefile
- test/test_bregman.py
- test/test_da.py
- test/test_gromov.py
- test/test_optim.py
- test/test_stochastic.py
- test/test_unbalanced.py
+ Some tests were unnecessarily long to run. 
+ Handled some warnings
> [MRG] Speedup tests

- setup.py
attempt to close #268
cc @zsteve
> we don't test with 3.5 but we already do with 3.9 so setup was not up to date

- ot/bregman.py
- ot/da.py
- ot/datasets.py
- ot/dr.py
- ot/gromov.py
- ot/lp/__init__.py
- ot/optim.py
- ot/partial.py
- ot/plot.py
- ot/sliced.py
- ot/smooth.py
- ot/stochastic.py
- ot/unbalanced.py
- ot/utils.py
A big part of the documentation has not been correctly compiled and should be corrected.
> [MRG] Docs updates

- examples/backends/plot_optim_gromov_pytorch.py
Fix small typos and a blank line (in the last part) for better example generation.
> [DOC] Minor changes for better doc generation in GW with Pytorch example

- setup.py
> [MRG] Don't install benchmarks

- examples/plot_OT_L1_vs_L2.py
> [MRG] minor spelling fix in example

- ot/bregman.py
- test/test_bregman.py
> [MRG] Fix barycenter mass

- RELEASES.md
- ot/weak.py
> [MRG] Wrong documentation in weak OT solver

- RELEASES.md
- examples/gromov/plot_gromov_barycenter.py
> [MRG] Gromov barycenter example bug

- RELEASES.md
- ot/__init__.py
Working on the next minor release (text + documentation)
> [MRG] Release 0.9.0

- docs/source/conf.py
- ot/optim.py
fix doc search with trick from:
https://github.com/readthedocs/sphinx_rtd_theme/issues/1452
> [MRG] debug documentation search

- .github/workflows/build_tests.yml
- .github/workflows/circleci-redirector.yml
- RELEASES.md
- ot/__init__.py
> [MRG] Fix circleci_redirector and codecov

- RELEASES.md
- ot/backend.py
- ot/gromov/_gw.py
- test/test_gromov.py
Making a weight parameter in FGW differentiable (so that it can be optimized on data).
> [MRG] make alpha parameter in FGW diferentiable

- .github/workflows/build_tests.yml
- RELEASES.md
- docs/Makefile
- examples/backends/plot_sliced_wass_grad_flow_pytorch.py
- examples/backends/plot_ssw_unif_torch.py
- examples/backends/plot_stoch_continuous_ot_pytorch.py
- examples/barycenters/plot_convolutional_barycenter.py
- examples/plot_OT_1D_smooth.py
- examples/sliced-wasserstein/plot_variance.py
- examples/sliced-wasserstein/plot_variance_ssw.py
- examples/unbalanced-partial/plot_regpath.py
+ Remove tests on old python versions on windows and macos that take forever to run
+ Speedup doc build : 
+ On Github action 21min -> 12 min
+ On circleCI 22min -> 15-19 min (damn you circleci!)
> [MRG] Update tests and documentation

- .circleci/config.yml
- RELEASES.md
- docs/source/conf.py
- examples/gromov/plot_barycenter_fgw.py
- ot/utils.py
- test/test_utils.py
Change test and documenation for cdist function
> [FIX] Change in scipy cdist API

- ot/da.py
Fix docstring formatting for reference.
Otherwise it split the name of the paper treating the second line as a new paragraph.
n/a
> [DOC] Fix reference for closed form linear GW

- RELEASES.md
- ot/gromov/_bregman.py
- test/test_gromov.py
> [WIP] Fix matrix feature shape in entropic FGW barycenters

- ot/bregman/_geomloss.py
- ot/solvers.py
Fixing tiny typos I found while reading the doc
> tiny typos in doc

- ot/__init__.py
> [MRG] Release 0.9.3

- RELEASES.md
- docs/source/all.rst
- examples/others/plot_lowrank_sinkhorn.py
- ot/__init__.py
- ot/lowrank.py
Fix some tipos and issues with thumbnail not showing low-rank sinkhorn plots + autosummary for ot.lowrank
> [MRG] fix doc+example lowrank sinkhorn

- RELEASES.md
- ot/__init__.py
This PR changes the version to 0.9.5dev0  now that release 0.9.4 has been published.
> Change version to 0.9.5dev0
