PythonOT/POT

- ot/bregman.py
Doing the computation this way is equivalent and allows to reduce the space complexity required from O(max(a, b)^2) to O(a*b) (especially usefull to transport a small number of sources example to a lot of target)
This also allows to decrease the computation time.
> Performance improvement sinkhorn

- ot/da.py
- ot/gpu/bregman.py
- ot/gpu/da.py
- test/test_gpu_sinkhorn_lpl1.py
- instead of updating individually for each target examples, update for all target examples at once using numpy functions. This allows for a faster computation (for me, divided by 4 on 3000*100 random matricies and random labels in [0,1]).
- if I understoud correctly, a value of -1 in the array labels_a meant that we didn't have a label for this example. But in machine learning, we often encounter the binary case where we say we have the positive class (+1) and negative class (-1); thus with a dataset like this, the algorithm wouldn't work as expected. I replaced the default value for 'no label' to '-99' instead of '-1', and I added a parameter to modify it.
> performance improvement sinkhorn lpl1

- README.md
Now that POT is in conda-forge (https://github.com/conda-forge/staged-recipes/pull/3332 / [feedstock repo](https://github.com/conda-forge/pot-feedstock/)), might as well put that in the installation instructions.
Note that it's available on Windows too, and [this basic test](https://github.com/conda-forge/pot-feedstock/blob/master/recipe/run_test.py) at least runs.
> add conda-forge to installation instructions

- .gitignore
- .travis.yml
- examples/plot_OTDA_2D.py
- examples/plot_OTDA_classes.py
- examples/plot_OTDA_color_images.py
- examples/plot_OTDA_mapping.py
- examples/plot_OTDA_mapping_color_images.py
- examples/plot_OT_1D.py
- examples/plot_OT_2D_samples.py
- examples/plot_OT_L1_vs_L2.py
- examples/plot_WDA.py
- examples/plot_barycenter_1D.py
- examples/plot_compute_emd.py
- examples/plot_optim_OTreg.py
- ot/bregman.py
- ot/da.py
- ot/datasets.py
- ot/dr.py
- ot/gpu/bregman.py
- ot/gpu/da.py
- ot/optim.py
- ot/plot.py
- ot/utils.py
- requirements.txt
- setup.cfg
- test/test_emd_multi.py
- test/test_gpu_sinkhorn.py
- test/test_gpu_sinkhorn_lpl1.py
- test/test_load_module.py
@rflamary @ncourty any opinion on this? shall I continue?
big questions are
- ok to adopt pep8?
- do you agree to use py.test for more standard testing mechanism?
don't merge yet. Just tell me what you think.
> [MRG] flake8 + pimp example figures

- ot/da.py
- ot/lp/EMD.h
- ot/lp/EMD_wrapper.cpp
- ot/lp/__init__.py
- ot/lp/emd_wrap.pyx
- ot/utils.py
- Allow to modify the maximal number of iterations
- Display an error message in the python console if the solver encountered an issue
> Changes to LP solver:

- ot/da.py
I have added the use of log parameter in class EMDTransport and SinkhornLpL1Transport, where it was not used. Related discussion here: https://github.com/rflamary/POT/issues/43
> Using log parameter

- setup.py
Add information for a markdown long description in pipy (which is now compatible).
This aim at avoiding this:
https://pypi.org/project/POT/0.4.0/
and getting something such as this:
https://pypi.org/project/POT/0.3.1/
The fail was due to  lack of pandoc on my machine at the time.
> add markdown format for pipy

- Makefile
- README.md
- examples/plot_barycenter_lp_vs_entropic.py
- ot/bregman.py
- ot/lp/__init__.py
- ot/lp/cvx.py
- requirements.txt
- test/test_gpu.py
- test/test_ot.py
The PR add the following:
+ LP solver for for Wassersein barycenters (do not scale at all but still nice for comparison).
+ Can choose the solver between scipy.optimize and cvxopt (the new interior point solver of scipy as pretty good)
+ Documentation and test for the solver, update of the README.
+ Example of comparison between LP and regularized barycenter :
> LP Wasserstein barycenter with scipy linear solver and/or cvxopt

- README.md
- examples/plot_free_support_barycenter.py
- ot/lp/__init__.py
- ot/lp/cvx.py
- test/test_ot.py
2-Wasserstein Barycenter algorithm with an example script. Optimization is carried over the locations of the support (not the weights). Only the unregularized case now. Regularized version will come soon.
> Free support barycenters

- ot/bregman.py
- ot/utils.py
Speed-up in 3 places:
- the computation of pairwise distance is faster with sklearn.metrics.pairwise.euclidean_distances
- faster computation of K = np.exp(-M / reg)
- faster computation of the error every 10 iterations
Example with this little script:
import time
import numpy as np
import ot
rng = np.random.RandomState(0)
transport = ot.da.SinkhornTransport()
time1 = time.time()
Xs, ys, Xt = rng.randn(10000, 100), rng.randint(0, 2, size=10000), rng.randn(10000, 100)
transport.fit(Xs=Xs, Xt=Xt)
time2 = time.time()
print("OT Computation Time {:6.2f} sec".format(time2-time1))
transport = ot.da.SinkhornLpl1Transport()
transport.fit(Xs=Xs, ys=ys, Xt=Xt)
time3 = time.time()
print("OT LpL1 Computation Time {:6.2f} sec".format(time3-time2))
Before
OT Computation Time  19.93 sec
OT LpL1 …
> Speed-up Sinkhorn

- Makefile
- ot/bregman.py
Hello,
Since @LeoGautheron and the sklearn devellopers opened my  eyes about einsum, I found some new speedup especially on the test of violation of the marginals constraints. I also use einsum to compute the final loss for paralell sinkhorn computations.
With the following benchmark 
```python
import time
import numpy as np
import ot
rng = np.random.RandomState(0)
n=5000
d=2
b=5
reg=1e0
Xs, ys, Xt = rng.randn(n, d), rng.randint(0, 2, size=n), rng.randn(n, d)
a=ot.unif(n)
B=np.ones((n,b))/n
M=ot.dist(Xs,Xt)
time1 = time.time()
res=ot.sinkhorn(a,a,M,reg,verbose=True)
time2 = time.time()
print("Sinkhorn Computation Time {:6.2f} sec".format(time2-time1))
time1 = time.time()
res=ot.sinkhorn(a,B,M,reg,verbose=True)
time2 = time.time()
print("Multi Sinkhorn Computation Time {:6.2f} …
```
> Speedup Sinkhorn with einsum + bench

- ot/stochastic.py
Hello!
I would like to request a PR for the stochastic framework. It is a small modification of the dual solver. I just update the dual variable coordinates which are in the batch. Because the partial gradients are sparse, it avoids to update the dual variables with 0.
I tested it : 
For uniform distributions
len(\alpha) = 700
len(\beta) = 500
batch_size = 200
num_iter = 100000
time before modification : 191 s
time after modification : 177 s
So as you can see, there is a huge potential in large scale settings. 
Thank you.
> better implementation on gradient updates

- README.md
- docs/source/all.rst
- docs/source/conf.py
- ot/gpu/__init__.py
- ot/gpu/bregman.py
- ot/gpu/da.py
- ot/gpu/utils.py
- test/test_bregman.py
- test/test_gpu.py
The PR is a cupy implementation of the functions currently implemented in ot.gpu. I also removed all the classes that were deprecated anyways. It still needs proper updated test but i like this solution since it stays mostly compatible with the old ot.gpu.
I have received a large number of queries about ot.gpu but cudamat is not maintained and the problem will only grow so we need to do something before release 0.5. 
This solution is far less elegant than PR #32 of @toto6  with all the decorators but having a cupy specific implementation leaves more room for code optimization than a generic implementation IMHO. Which means that we can make it better in the future without compromizing the numpy implmentation.
I give an example of use for the ot.gpu functions below with different format for …
> [MRG] New ot.gpu with cupy

- examples/plot_stochastic.py
- ot/stochastic.py
I fixed the doc for ot.stochatic and plot_stochastic.
> [MRG] fixed doc for stochastic and plot_stochastic

- examples/plot_otda_color_images.py
The prediction images for Sinkhorn used the ot_emd object instead of ot_sinkhorn
> Corrected the Sinkhorn prediction images

- .travis.yml
- ot/bregman.py
- test/test_bregman.py
This PR adresses the bug reported in Issue #75.
What has been done:
+ Add a test that check with  `log=True` works for all sinkhorn variants
+ Correct the bug #75 in greenkhorn
+ Add conversion to np.array inside greenkhorn (same as sinkhorn now)
> Bug Greenkhorn with log=True

- README.md
- examples/plot_OT_2D_samples.py
- ot/bregman.py
- ot/stochastic.py
- test/test_bregman.py
Hello,
I am sending a PR. The PR has for purpose to add empirical functions. Mainly, the added functions just need the original source data, target data and the regularization parameter for entropic OT. In the PR, you will find:
- Function to calculate the OT transportation matrix from empirical data
- Function to calculate the OT loss from empirical data
- Function to calculate the Sinkhorn divergence from empirical data
- Tests for those functions
- Example
- Fix doc stochastic OT
Those functions will be in the bregman.py file. Their test functions will be in test_bregman.py. Finally, their examples have been put in plot_OT_2D_samples.py.
> add empirical sinkhorn and sinkhorn divergence functions

- ot/da.py
Adresses issue #83  and introduces further corrections to the docstrings in ot.da
> Fixed multiple docstring issues

- README.md
- docs/source/all.rst
- examples/plot_UOT_1D.py
- examples/plot_UOT_barycenter_1D.py
- ot/__init__.py
- ot/bregman.py
- ot/unbalanced.py
- test/test_unbalanced.py
new unbalanced module for UOT with KL relaxation with the funcs:
- `sinkhorn_unbalanced`:  generalized Sinkhorn to compute W
- `barycenter_unbalanced`: unbalanced Wasserstein barycenter
- Tests of convergence for both algorithms
- Examples `plot_UOT_1D` and `plot_UOT_barycenter_1D` with unbalanced gaussian distributions.
> [MRG] Add Unbalanced KL Wasserstein distance + barycenter

- README.md
- ot/__init__.py
- ot/lp/__init__.py
- ot/lp/emd_wrap.pyx
- test/test_ot.py
Hi there,
I started coding a specific EMD for mono-dimensional case (i.e. when sorting both arrays is enough).
Doc is missing for the moment (will do that asap), but a basic implementation that covers the non uniform weight case and tests that checks if the results are coherent with EMD are already there.
On my machine, I ran the following timing test:
```python
>>> n = 20000
>>> m = 3000
>>> u = np.random.randn(n, 1)
>>> v = np.random.randn(m, 1)
>>> ot.tic(); ot.emd_1d([], [], u, v, metric='sqeuclidean'); ot.toc()
array([[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
...,
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.],
[0., 0., 0., ..., 0., 0., 0.]])
Elapsed time : 2.3728668689727783 s
2.3728668689727783
>>> ot.tic(); M = …
```
> [MRG] EMD and Wasserstein 1D

- .travis.yml
- ot/bregman.py
- ot/gpu/bregman.py
- ot/lp/__init__.py
- ot/stochastic.py
- ot/unbalanced.py
- ot/utils.py
- test/test_gpu.py
- test/test_ot.py
Hi there,
As it is coded at the moment, doctests are not checked by Travis, since the call in `test_ot` does not raise any error. This PR is an attempt to fix that.
> [MRG] Have Travis actually execute doctests

- ot/unbalanced.py
- test/test_unbalanced.py
This PR complements #87 by adding:
I am also thinking when a numerical error is encountered, Instead of stopping and returning the previous value, we could automatically switch to log-domain, what do you think ?
> [WIP] Add stabilization for the unbalanced module

- examples/plot_barycenter_lp_vs_entropic.py
- examples/plot_free_support_barycenter.py
Hello,
I am sending a pull request after catching some typos in barycenter examples. In the PR you will find:
- Fix comments in plot_free_support_barycenter.py 
- Fix plot in plot_barycenter_lp_vs_entropic.py
> [MRG] corrected typos in barycenter examples

- .travis.yml
- ot/da.py
- ot/unbalanced.py
- ot/utils.py
- test/test_da.py
This PR is primarily adds the unbalanced sinkhorn method to the domain adaptation classes. When the other sinkhorn methods will be implemented (eg stabilized) they will also be supported by the parameter method, which will now raise an error according to what is in unbalanced.py
In addition: 
- a small bug in the unbalanced.py warnings is corrected.
- Giving a norm value other than what is allowed and implemented will raise an error. I did that because I accidentally wrote something else and could not figure out where the bug was. Can be modified to raise a warning, but I think it should be an error.
> [MRG] Adds Unbalaced transport to domain adaptation methods + bugfixes

- .gitignore
- docs/source/quickstart.rst
- ot/__init__.py
- ot/bregman.py
- ot/da.py
- ot/unbalanced.py
- test/test_bregman.py
- test/test_unbalanced.py
A follow-up of the unfinished PR #95. 
Adresses the following:
> [MRG] Add stabilization for unbalanced OT and barycenter computation

- ot/bregman.py
- ot/unbalanced.py
> MRG: Forgotten weights arg in barycenter funcs

- ot/gromov.py
- ot/optim.py
- test/test_gromov.py
- test/test_optim.py
Hello,
I am sending a new PR to solve a 'log' bug in the gromov_wasserstein2 function. Indeed, because of a variable name mismatch, the log was overwritten and was always returned.
In this PR, you will find:
Bug 'log' correction
Test log=False for gromov_wasserstein2
Removing 'H entropy' from doc for gromov_wasserstein and gromov_wasserstein2
numItermax bug for emd function inside cg function. The number of iter was fixed to 100.000 and could not be modified.
Test numItermaxEmd > 100000 for cg.
> [MRG] Fix bug in gromov_wasserstein and gromov_wasserstein2

- .gitignore
- ot/lp/EMD.h
- ot/lp/EMD_wrapper.cpp
- ot/lp/__init__.py
- ot/lp/emd_wrap.pyx
- ot/lp/network_simplex_simple.h
- test/test_ot.py
In this PR, i work on making the emd function able to return sparse OT matrices.
> [MRG] Sparse emd solution

- ot/lp/__init__.py
- test/test_ot.py
Hello,
I am sending a PR with a patch to issue 114. In this PR, you will find:
. An assert condition (M dimensions with a and b)
. Test to catch the Assertion error.
> [MRG] Add assert for emd dimension mismatch

- ot/lp/__init__.py
- ot/lp/emd_wrap.pyx
- test/test_ot.py
I just discovered this important bug in the `ot.emd``function and it feels like opening pandoras's box.
I added in the fisrt commit a test that checks that the constraints are satisfied and we can see in the travis build that the test fails. This comes from the fact that the c++ emd solver is sparse in the sens that if a weight is 0 it will discard the bin and solve a smaller subproblem on the histograms that have non-zero weights. It works very well and is very efficient in practice bug it does not return proper dual variables because it sets the value for the bins with 0 weight to 0 which can lead to constraint violation in practice.
What I will do in this PR:
The post-processing is actually necessary when trying to estimate correct dual variable from the optimal sub-problem if we want …
> [WIP] Bug on dual potential (constraint violation when some weights are 0)

- ot/bregman.py
- test/test_bregman.py
Thank you for your awesome package!
The code and examples for `ot.bregman.convolutional_barycenter2d` assumes a symmetric image. This PR changes the kernel to allow for non-symmetric images and adds a simple test of this functionality.
This addresses Issue #124
> [MRG] Fix convolutional_barycenter2d kernel for non-symmetric images

- ot/gromov.py
The `alpha` trade-off parameter of the Fused Gromov Wasserstein implementation was not used correctly: what was computed was 
```
(arg)min_\gamma <\gamma, M>_F + \alpha \sum L(C1_{i,k},C2_{j,l}) T_{i,j} T_{k,l}
```
instead of the convex combination
```
(arg)min_\gamma (1 - \alpha) <\gamma, M>_F + \alpha \sum L(C1_{i,k},C2_{j,l}) T_{i,j} T_{k,l}
```
Even though the two are mathematically equivalent up to a rescaling of alpha, it was not consistent with the documentation. I changed the implementation so `optim.cg` is called with `cg(..., (1-alpha)*M, alpha, ...)` instead of `cg(..., M, alpha, ...)` which should be enough to fix this issue.
> [MRG] Fix Fused Gromov Wasserstein implementation

- ot/lp/__init__.py
- test/test_ot.py
Fixes https://github.com/rflamary/POT/issues/138
> [MRG] Fix ordering

- ot/lp/emd_wrap.pyx
So the code can be used in parallel threads.
> Add nogil to EMD_wrap

- ot/lp/emd_wrap.pyx
> fix array bounds issue

- examples/domain-adaptation/plot_otda_color_images.py
- examples/domain-adaptation/plot_otda_linear_mapping.py
- examples/domain-adaptation/plot_otda_mapping_colors_images.py
- examples/gromov/plot_gromov_barycenter.py
The new version of flake8 complains about the variable name `I` now; it didn't before. Rename these to `img`, which is better anyway.
> rename I to img in examples, since flake8 complains now

- codecov.yml
Ignore gpu for code coverage (it cannot be tested)
> [MRG] Update codecov.yml

- ot/optim.py
Issue: [line_search_armijo returns alpha > 1](https://github.com/PythonOT/POT/issues/184)
> Restrict Armijo linesearch function step to be at most 1

- ot/bregman.py
- ot/optim.py
Reverts PythonOT/POT#195
cancel merge until better debug
> Revert "[WIP] Update bregman.py : barycenter_sinkhorn function"

- ot/bregman.py
- ot/lp/__init__.py
- [ x] Docs change / refactoring / dependency upgrade
https://github.com/PythonOT/POT/issues/200
I can't render the doc locally so not tested
- [ x] The documentation is up-to-date with the changes I made.
- [x ] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
> Correct documentation for support barycenter

- ot/optim.py
- test/test_optim.py
scipy.optimize.linesearch.scalar_search_armijo can return alpha=None ([function definition](https://github.com/scipy/scipy/blob/master/scipy/optimize/linesearch.py#L689)). In optim.py:line_search_armijo as part of a previous issue #184, we restrict the value of alpha to be at most 1 with min(1, alpha) but this throws an Exception when alpha is None. In this PR, we just check the value of `alpha` is not `None` when making the comparison with `1`.
Issue: [https://github.com/PythonOT/POT/issues/198](https://github.com/PythonOT/POT/issues/198)
> Check if alpha is not None when restricting it to be at most 1

- .github/requirements_strict.txt
- .github/workflows/build_tests.yml
- .gitignore
- Makefile
- ot/lp/__init__.py
- test/test_da.py
+ cleanupothe build_minimal that had numpy, scipy cython version forced and was failing
+ add a separate pep8 build so taht all teh otehr test can still run in pep8 fails
The build was failing in all the PR becausqe of that.
The pep8 was a pain when a new commit was necessary in order to get tye output of the tests when pep8 failure
> [MRG] Cleanup minimal build and add separate build for pep8

- ot/lp/network_simplex_simple.h
- [ X] Bug fix (non-breaking change which fixes an issue)
Problem INFEASIBLE cast where it should not happen.
Fixes https://github.com/PythonOT/POT/issues/126
Fixes #93 
The minimal code to repdroduce the bug is now working.
A user tested on its own data and now the problem is also working
> change precision EPSILON in C code

- .github/workflows/build_tests.yml
- ot/torch/lp.py
- ot/torch/utils.py
- test/test_torch.py
I saw the torch branch for LP stuff.
Would you be interested in my implementation for the 1d EMD (and the sliced wasserstein with it)?
I'm not a huge fan of Pytorch so I can't vouch that what I'm doing here is the best implementation, but it feels to me like it should be fairly ok for batched inputs which is what you want for slice stuff anyway.
>  [WIP] small tentative for EMD 1D in torch

- .github/workflows/build_tests.yml
- ot/utils.py
* Add new python versions 3.9 in test (and remove 3.5 that is end of life)
* Add more versions in macosx and windows 
* Correct pickling problem for paralell implementation of emd (now deactivated on macos and windows)
> [MRG] Add new python versions for tests (also macos and windows)

- ot/da.py
- ot/dr.py
- ot/gpu/bregman.py
- ot/gromov.py
- ot/lp/cvx.py
- ot/optim.py
- test/test_bregman.py
+ removed warnings for docstrings
+ Correct test for bregman.py so that the distributions given for barycenter sum to 1.
> [MRG] Cleanup test warnings

- examples/backends/plot_wass2_gan_torch.py
- examples/domain-adaptation/plot_otda_color_images.py
- examples/domain-adaptation/plot_otda_mapping_colors_images.py
- ot/backend.py
This PR introduce the following changes
The memory leak was due to the creation of a new class for each call to ot.emd2 that used torch tensors in their scope which meant that tose tensors could not be de-allocated by the garbage collector. It has been solved by using a torch function that takes both inputs output value and gradients as input bu provides gardients only for the inputs (see set_gradients(self, val, inputs, grads) function on torch backend)
> [WIP] Add Wasserstein GAN and debug memory leak

- docs/source/conf.py
- examples/backends/plot_wass2_gan_torch.py
All in the title ;)
Also added an animation for the trajectory of the generated samples
> [MRG] Update example GAN to avoid the 10 minute CircleCI limit

- .circleci/config.yml
- ot/bregman.py
- test/test_bregman.py
> [MRG] Batch/Lazy Log Sinkhorn Knopp on samples

- ot/optim.py
- test/test_da.py
- test/test_optim.py
Resolves #281, can be reproduced consistently with numpy seed 39.
The test file for da.py sometimes crashes because the alpha variable in optim.cg might be None. This is due to the fact that the derphi variable is close to 0 (i.e. the algorithm has already converged). We solve this by setting alpha to 0, and therefore breaking the loop and returning the computed value.
Tested on Linux
> [MRG] Regularized OT (optim.cg) bug solve 

- ot/bregman.py
- ot/gpu/bregman.py
- ot/gpu/da.py
Resolves #284, Resolves #287 
Tests on GPU were failing
Tested on Linux
> [MRG] GPU bugs solve

- ot/utils.py
- test/test_utils.py
Resolves #305, also allows the usage of weights (otherwise wminkowski is not a valid metric contrary to what POT doc suggests)
Tests ran locally without a hitch
> [MRG] Distance calculation bug solve

- .circleci/config.yml
- examples/plot_Intro_OT.py
- ot/backend.py
- test/test_ot.py
* Fixes Issue #309 about porblem in scaling of gradients
* Correct documentation problem in examle Intro_OT
* Fix upload of documentation when release
> [WIP] Fix gradient scaling bug in emd

- ot/optim.py
- test/test_optim.py
Attempt to resolve #311. 
This bug appeared on multiple occasions (#281, #311 as far as I'm aware) due to the fact that line_search_armijo could return None as an alpha if no valid value was found. This behaviour is faulty and might be a cause of bugs in the future. From now on,  this function returns 0 if no alpha value was found, meaning convergence point was reached.
Tested with the data provided by issue #311
> [MRG] SinkhornL1L2Transport bug

- ot/optim.py
Resolves #311 
Also setting a minimum value for alpha from now on.
> [MRG] SinkhornL1L2 bug solve

- README.md
- ot/backend.py
- ot/gromov.py
- ot/optim.py
- test/test_backend.py
- test/test_bregman.py
- test/test_gromov.py
Cupy backend
Tested with cupy 9.0.0
Make pytest will show that cupy's tests are very slow. This is my outlook on that:
For gromov, generator.choice is used in numerous functions but for cupy it requires sending the p argument back on the CPU. These recurrent operations are limited by memory bandwidth and penalises GPUs pretty harshly. 
For other tests, GPUs have an advantage for bigger calculation and tests are usually done with tiny problems, for which CPUs might be faster (no overhead because no transfer towards and from GPUs and very quick memory).
To be fair, I tried to resolve different-sized problems on sinkhorn (using pretty much the code from
test/test_gpu.py::test_gpu_sinkhorn). Here are the results (averaged on 500 runs) :
| Size | Sinkhorn (Numpy) | Sinkhorn (ot.gpu) | Sinkhorn …
> [MRG] Cupy backend

- ot/gromov.py
- test/test_gromov.py
To fix the issue #317 
pytest on `test` folders
> [MRG] Fix issue 317

- .github/requirements_test_windows.txt
- README.md
- benchmarks/__init__.py
- benchmarks/benchmark.py
- benchmarks/emd.py
- benchmarks/sinkhorn_knopp.py
- docs/requirements.txt
- docs/requirements_rtd.txt
- docs/source/.github/CODE_OF_CONDUCT.rst
- docs/source/.github/CONTRIBUTING.rst
- docs/source/code_of_conduct.rst
- docs/source/conf.py
- docs/source/contributing.rst
- docs/source/index.rst
- ot/backend.py
- ot/bregman.py
- ot/da.py
- ot/datasets.py
- ot/dr.py
- ot/gromov.py
- ot/lp/solver_1d.py
- ot/plot.py
- requirements.txt
- test/conftest.py
- test/test_1d_solver.py
- test/test_backend.py
- test/test_bregman.py
- test/test_gromov.py
- test/test_ot.py
- test/test_sliced.py
- Backend for tensorflow. 
- Also adds a benchmark folder which allows to easily benchmark every backend and present results in a html table (compatible with github comments and PR text).
- Also replaced m2r2 by myst_parser. It allows to use markdown files in our official docs. Myst_parser seems more maintained. It also happens to solve the issue with internal links introduced by the m2r2 update few PRs ago.
Note that tensorflow does not know how to transpose inplace, which can have a negative impact on performance for any function which requires the usage of a transpose (More information here: https://www.tensorflow.org/api_docs/python/tf/transpose#expandable-1)
Note that nothing was done regarding the device consistency of our calculation (unlike TorchBackend for instance). This is due …
> [MRG] Tensorflow backend & Benchmarker & Myst_parser

- .circleci/config.yml
- RELEASES.md
- ot/__init__.py
This changed version number to 0.8.1.0 and hopefully will correct the doc build on master
> [MRG] Release 0.8.1.0 and correct doc build

- RELEASES.md
- ot/backend.py
`ValFunction` should not be instantiated since `autograd` functions are
supposed to only ever use static methods. This solves a warning message
raised by PyTorch.
The warning message of PyTorch indicates that this behaviour may raise
an error in future versions.
With PyTorch 1.10.1+cu102, using OT on a `tensor` with a gradient, the following warning message is raised:
> [....] valfunction should not be instantiated. Methods on autograd functions are all static, so you should
> invoke them on the class itself. Instantiating an autograd function will raise an error in a future version
> of PyTorch.
This pull request fixes the instantiation, thus also fixing issue #337.
Used my own code with the fork of `POT`. The warning is not raised any more; further behaviour remains exactly the same.
> [MRG] Fix instantiation of `ValFunction` (which raises a warning with PyTorch)

- RELEASES.md
- ot/dr.py
- test/test_dr.py
The current implementation of the WDA dimensionality reduction runs into numerical issues (nans and infs) with small values of the regularization parameter (reg). This PR re-implements the sinkhorn algorithm in log-domain, which allows to use WDA with much smaller reg parameter values.
A new regression test was added that runs WDA with small reg, the current master version fails it and this PR passes.
> [MRG] Implement Sinkhorn in log-domain for WDA

- RELEASES.md
- docs/source/all.rst
- ot/lp/__init__.py
- test/test_ot.py
- test/test_utils.py
* Backend implementation of `ot.lp.free_support_barycenter`
* New tests for the function on backend
> [MRG] Backend implementation of the free support barycenter

- .github/workflows/build_wheels.yml
- .github/workflows/build_wheels_weekly.yml
- RELEASES.md
- docs/source/quickstart.rst
- pyproject.toml
- requirements.txt
- setup.py
- test/test_utils.py
this PR is a local (branch) version of #347 that will actually run the wheel building.
Fixes #346
> [MRG] Build POT against oldest-supported-numpy (local PR)

- .circleci/config.yml
- RELEASES.md
The objective is to have links to Issues and PR when in the Release page in the docuemnation.
It is done with a simple sed before building the doc
> [MRG] Proper links in release file in documentation

- RELEASES.md
- ot/gromov.py
- test/test_gromov.py
The backpropagation is not working in gromov_wasserstein2 if the given tensors are located on a GPU. This is due to the fact that part of the computation is performed with numpy and  the device was forgotten when casting back to torch. 
Resolves #351
> [MRG] Gromov_Wasserstein2 not performing backward properly on GPU

- RELEASES.md
- examples/backends/plot_dual_ot_pytorch.py
- examples/backends/plot_stoch_continuous_ot_pytorch.py
- ot/stochastic.py
- test/test_stochastic.py
Add differentiable losses for stochastic optimization of entropic and quadratic OT and functions to recover the OT plkan thanks to the primal-dual relations.
Adds two exmapels of use of those  functions:
+ [Dual OT solvers for entropic and quadratic regularized OT with Pytorch](https://output.circle-artifacts.com/output/job/9d1e10e8-3efa-4d04-9146-886824b2c866/artifacts/0/dev/auto_examples/backends/plot_dual_ot_pytorch.html#sphx-glr-auto-examples-backends-plot-dual-ot-pytorch-py)
+ [Continuous OT plan estimation with Pytorch](https://output.circle-artifacts.com/output/job/9d1e10e8-3efa-4d04-9146-886824b2c866/artifacts/0/dev/auto_examples/backends/plot_stoch_continuous_ot_pytorch.html#sphx-glr-auto-examples-backends-plot-stoch-continuous-ot-pytorch-py)
> [WIP] Add backend dual loss and plan computation for stochastic optimization or regularized OT

- CONTRIBUTORS.md
- README.md
- RELEASES.md
- examples/backends/plot_sliced_wass_grad_flow_pytorch.py
- examples/barycenters/plot_generalised_free_support_barycenter.py
- examples/barycenters/plot_generalized_free_support_barycenter.py
- ot/__init__.py
- ot/lp/__init__.py
- test/test_ot.py
- test/test_partial.py
- Added a `generalized_free_support_barycenter` solver  in `ot/lp/__init__.py` (next to `free_support_barycenter`)
- Added an associated example `examples/barycenters/plot_generalized_free_support_barycenter.py`
- Fixed doc for `free_support_barycenter` (mis-numbered/missing references + added details on variable names)
- Fixed a reproducibilty issue in  a test for a partial gromov solver
Implements the article "Generalised Wasserstein Barycenter" [42]
[42] DELON, Julie, GOZLAN, Nathael, et SAINT-DIZIER, Alexandre.
Generalized Wasserstein barycenters between probability measures living on different subspaces.
arXiv preprint arXiv:2105.09755, 2021.
Added tests in `tests_ot.py`, accounting for dimensionality, optional arguments and backends
> [WIP] Generalized Wasserstein Barycenters 

- RELEASES.md
- ot/lp/network_simplex_simple.h
- ot/lp/network_simplex_simple_omp.h
Adds flags to disable std::cerr reporting in the cpp backend. Adds parameter `ot.backend.use_cerr` as parameter and `ot.backend.get_cerr()` getter to enable/disable `cerr` reporting inside of python. The parameter defaults to False.
We are using POT inside of jupyter notebook and running into a problem that hits its iter limits. The warnings flood our console. Because the backend code is calling std::cerr directly, rather than passing the error string up to the python stderr stream, traditional context management based redirection (or simply killing sys.stderr inside of python)  does not work.
Have tested the basic use case and enable/disabling the cerr. Works in ipython on 3.9.7.
- [x ] I have read the [**CONTRIBUTING**](CONTRIBUTING.md) document.
- [x ] The documentation is up-to-date …
> [WIP] Silence std::cerr calls inside of python

- ot/utils.py
Resolves #378. The `dist` function needs an extra check that it's actually a string before calling a string method - mainly just in case the metric is a callable.
> [MRG] Check metric is a string

- RELEASES.md
- ot/lp/EMD.h
- ot/lp/EMD_wrapper.cpp
- ot/lp/emd_wrap.pyx
- ot/lp/network_simplex_simple.h
- ot/lp/network_simplex_simple_omp.h
- test/test_unbalanced.py
When the OpenMP version of EMD was added, the computation of the plan was converted to 64 bits. However, one variable was forgotten, which is the max number of iterations. In the C code, it is a size_t variable, hence usually 64 bits, but the Cython link between C and Python uses an int to store the value. I intend to make it 64 bits as well to allow high numbers of iterations.
I run all tests on Jean Zay.
> [MRG]  numItermax in 64 bits in EMD solver

- Makefile
- RELEASES.md
- examples/backends/plot_sliced_wass_grad_flow_pytorch.py
- ot/gromov.py
- ot/lp/cvx.py
- ot/unbalanced.py
Changing code for backend example
Resolves #389 
Tested on Jean Zay with a V100
> [MRG] Solve example throwing an error when executed on a GPU

- RELEASES.md
- test/test_bregman.py
> [MRG] Debug sinkhorn divergence bug and add proper test

- RELEASES.md
- codecov.yml
- docs/source/conf.py
Fi the issue with gallery subsection using the new parameter 
See
https://github.com/sphinx-gallery/sphinx-gallery/issues/935
https://github.com/sphinx-gallery/sphinx-gallery/pull/944
Thanks so much to @alexisthual for allowing that on sphinx-gallery.
> [MRG] Proper subsections in gallery

- ot/gromov.py
The docstring of ot.gromov.init_matrix was not accurate. The documented parameters were C1, C2, T and p, although the function's parameters are C1, C2, p, q and loss_fun. The single commit of this PR fixes this issue.
The modification cannot be tested.
> [MRG] update docstring of ot.gromov.init_matrix

- RELEASES.md
- ot/helpers/pre_build_helpers.py
- ot/lp/network_simplex_simple_omp.h
- setup.py
- test/test_ot.py
Removes numpy ccompiler dependency. Replaces it with setuptools. The solution is based on scikit-learn (https://github.com/scikit-learn/scikit-learn/blob/main/sklearn/_build_utils/pre_build_helpers.py)
Resolves #408.
> [MRG] Replaces numpy compiler with setuptools

- ot/bregman.py
…c term is not taken into account.
Added a short mention in the doc of `ot.bregman.empirical_sinkhorn_divergence` to mention that the entropic contribution is not taken into account. 
Suggested by @rflamary in Issue #421 . Did an independent PR to avoid confusion with the corresponding fix.
> [MRG] Change Doc empirical_sinkhorn_div to reflect what is computed

- RELEASES.md
- ot/bregman.py
Variable default values. 
Fix small typo in the code, where the parameter `stopThr` in `empirical_sinkhorn_divergence` was useless because subcalls used `stopThr=1e-9` instead of `stopThr=stopThr`. 
Same for a similar instance occuring in `sinkhorn_epsilon_scaling`. 
Documented in Issue #421 .
> [MRG] Fix#421 pass stopThr to the sinkhorn function in empirical_sinkhorn_divergence

- RELEASES.md
- ot/bregman.py
- test/test_bregman.py
`warn` argument was not passed downstream `sinkhorn_knopp` and `sinkhorn_log` methods and hence it was not possible to suppress warnings appearing inside those methods. It's fixed now.
> [MRG] Fix warning bug in sinkhorn2

- CONTRIBUTORS.md
- RELEASES.md
- docs/source/all.rst
- docs/source/quickstart.rst
- examples/domain-adaptation/plot_otda_linear_mapping.py
- examples/gromov/plot_barycenter_fgw.py
- ot/__init__.py
- ot/da.py
- ot/datasets.py
- ot/gaussian.py
- test/test_da.py
- test/test_gaussian.py
This introduce Gaussian modules, a file comprising all the modules of optimal transport for Gaussian distributions. 
The OT_mapping_linear moved from da.py to gaussian.py. 
I added Bures Wasserstein distance to gaussian.py.
Also update examples/gromov/plot_barycenter_fgw.py to fit the new networkx API
Add new methods for Gaussian distributions.
The test for Bures Wasserstein distance is done on two 1D Gaussian distributions centered on 0 and 10 respectively. with the same variance The Bures Wasserstein distance is tested to be close of 10.
> [MRG] OT for Gaussian distributions

- RELEASES.md
- ot/da.py
Add parameter method to Sinkhrontransport int order to choose the method wanted for sinkhorn.
> [MRG] Add method argument to sinkhorn Transport

- .github/requirements_test_windows.txt
- RELEASES.md
- docs/requirements_rtd.txt
- ot/dr.py
- requirements.txt
This chage was  along time coming because we forced pymanopt version in requirement.txt. POT now runs witha recent erison of Pymanopts.
This will avoid people having porblem with recent pymanopts similarly to #370
> [MRG] Update pymanopt requirement and API for `ot.dr`

- RELEASES.md
- ot/lp/solver_1d.py
Remove redundant computation.
Remove redundant computation.
No related issue.
No need to test obviously.
> [MRG] Remove redundant abs()

- RELEASES.md
- ot/partial.py
- test/test_partial.py
The functions `partial_wasserstein`, `partial_wasserstein2` and `entropic_partial_wasserstein` have been adapted to work with any backend (not only numpy) and are tested with torch. In particular, backward passes through them are tested.
The functions mentioned above did not leverage the `nx` backend.
Forward and backward passes of the functions mentioned are tested with torch.
> [MRG] Make partial_wasserstein, partial_wasserstein2 and entropic_partial_wasserstein work with backend

- examples/backends/plot_wass2_gan_torch.py
The code sample from the documentation page "Wasserstein 2 Minibatch GAN" has been updated to zero out the gradient after each batch. 
The issue was described in #464.  I also reviewed other sections in the documentation where the PyTorch optimizer is used, and found that all other code samples properly call `zero_grad()`.
I experimented with various optimizers and settings, such as `SGD`, but the difference in wall time was negligible. I'm not sure if it's worth updating for performance reasons alone. @rflamary let me know what do you think.
> [DOC] Fix gradient update for "Wasserstein 2 Minibatch GAN" example

- RELEASES.md
- ot/backend.py
- ot/gaussian.py
* Fixed typo in the documentation of the Bures-Wasserstein distance ($\Sigma_s$ instead of $\Sigma_s^{1/2}$).
* Faster way of computing the trace of the square-root of the product of $\Sigma_s$ and $\Sigma_t$.
The implementation is based on two facts:
1. The trace of $A$ equals the sum of its eigenvalues.
2. The eigenvalues of $\sqrt{A}$ are the square-roots of the eigenvalues of $A$.
Then, $\mathrm{tr}(\sqrt{A})$ is the sum of the square-roots of the eigenvalues of $A$.
See https://github.com/Lightning-AI/torchmetrics/issues/1705.
Computing the square-root of a matrix is slow and unstable.
The new implementation still passes the tests (at least with NumPy backend).
> Improve Bures-Wasserstein distance

- RELEASES.md
- ot/bregman.py
Replace call to `np.log` with call to a proper backend for the `barycenter_stabilized` procedure.
Otherwise, it fails with
```
RuntimeError: Can't call numpy() on Tensor that requires grad. Use tensor.detach().numpy() instead.
```
when called with PyTorch tensors that are marked with `required_grad`.
- [] All tests passed, and additional code has been **covered with new tests**.
> [MRG] Fix barycenter_stabilized with PyTorch and log set to True

- .github/CONTRIBUTING.md
- RELEASES.md
- docs/source/conf.py
- ot/backend.py
- ot/factored.py
- ot/solvers.py
Fix references to `jax` and `numpy` functions.
* added `jax` to the list of mappings (there's `:any:` reference onto `jax.numpy.array` from Quickstart)
* fixed manual references for `np.random.*` functions from backend docstrings (previous links were broken)
* removed `:any:` references from docstrings onto function parameters (`ot.solver`) to avoid warnings when building docs
* fixed markup for `ot.factored` so the references to other modules are working correctly
> [DOC] Fix references to JAX and numpy functions

- .github/workflows/build_tests_cuda.yml
CUDA test runner is not always available for energy reasons and should not be requires for all push to master.
> [FIX] remove CUDA test on push to master

- RELEASES.md
- ot/gromov/_semirelaxed.py
- test/test_gromov.py
Addition of differentiability over the trade-off parameter $\alpha$ in the `semirelaxed_gromov_wasserstein2` function in `ot/gromov/_semirelaxed.py`.
> [FEAT] Alpha differentiability in semirelaxed_gromov_wasserstein2

- ot/backend.py
- ot/partial.py
- ot/stochastic.py
- test/test_backend.py
With the current behavior, the `check_backend` helper fails when one of the arguments is a subtype of the base type of the backend. For instance, if one argument is a `memmap`, while it is still a `ndarray`, the `check_backend` raises a `ValueError`.
This PR makes the helper check the type of all arguments with `isinstance`. It also refactors the API to ease the backend management.
> [MTN] more permissive check_backend

- ot/gaussian.py
- ot/utils.py
- test/test_gaussian.py
Issue `UserWarning` when `ot.gaussian.empirical_bures_wasserstein_mapping` returns matrix of NaNs. This happens when min eigenvalue turns out to be negative in `sqrtm`, typically requires `reg` parameter to be increased.
New test case with a simple reproducer is added.
> [MRG] Issue warning when numerical error happens in `empirical_bures_wasserstein_mapping`

- ot/datasets.py
Switch from `np.random.randn` to `rng.randn` when generating `make_data_classif` dataset with `dataset='2gauss_prop'`.
It's not desirable to change global state. And it's already done for other datasets in the same function.
n/a
> Use local random state in `ot.datasets.make_data_classif`

- ot/gromov/_bregman.py
Remove `print` statement about input datatype.
Seems like this is a debugging leftover. This information is not really helpful as it doesn't change, and it makes harder to read output when `verbose` is set to `True`.
n/a
> Remove debug print statement from entropic FBG

- ot/dr.py
- ot/gromov/_dictionary.py
- ot/stochastic.py
- test/test_1d_solver.py
- test/test_bregman.py
- test/test_coot.py
- test/test_da.py
- test/test_dmmot.py
- test/test_dr.py
- test/test_gromov.py
- test/test_optim.py
- test/test_ot.py
- test/test_partial.py
- test/test_plot.py
- test/test_regpath.py
- test/test_sliced.py
- test/test_unbalanced.py
- test/test_utils.py
This is rather lengthy follow-up for #510. Hopefully I found all cases to update:
* manual seeding is removed from tests
* tests are now using local random state generators rather than global state
* functions that rely on randomization except `random_state` arguments now
To make reproducibility easier.
Test cases are updated accordingly. It's interesting that previously for some of them (specifically suites from test_gromov) required explicit seeding for tests to work. Now they rely on `random_state` passed into functions and don't break because of global state.
I guess new parameters added to the API should be mentioned in the RELEASE file.
> Overhaul random state management

- ot/gromov/_utils.py
- test/test_gromov.py
`ot.gromov._utils.init_matrix` raises `ValueError` when unknown `loss_fun` is given.
`ot.gromov._utils.init_matrix_semirelaxed` raises `NotImplementedError` for `loss_fun='kl_loss'`.
`ot.gromov._utils.init_matrix_semirelaxed` raises `ValueError` for unknown `loss_fun`.
Error message is rather hard to understand when unsupported loss_fun is used (as the code makes an attempt to call undefined function).
New test cases are provided.
> Validate `loss_fun` parameter in Gromov-Wasserstein utils

- ot/gromov/_bregman.py
- test/test_gromov.py
* explicitly check if `loss_fun` given is valid for all GW functions that take such the argument
* fix docstrings where it was still listed as a "callable" (not an option now, based on the code)
* update tests to check for validation
Unified approach to handling `loss_fun` parameter for all GW-related functions. Cleaner error message.
Also, note that before the changes, oftentimes function relied on the validation to happen rather deep in the call stack, for example in `init_matrix` helper. Which seems rather fragile when making changes in high-level modules (e.g. another set of low-level procedures could be used). 
Test cases are updated.
> `loss_fun` parameter validationf for entropic GW functions

- RELEASES.md
- ot/backend.py
- test/test_backend.py
Tweaked the code for get_backend so as to ignore None entries
This is a convenience addition for optional arguments:
```python
def f(a, b=None):
nx = get_backend(a, b)
```
will be nicer that
```python
def f(a,b=None):
if b is None:
nx = get_backend(a)
else:
nx = get_backend(a, b)
```
especially in the case where there are a lot of optional arrays, where the amount of required `if` statements is combinatorial.
Added a test in `test/test_backend.py`. Ran and passed the test workflow. 
- [] All tests passed, and additional code has been **covered with new tests**.
> [MRG] get_backend compatibility with None entries

- ot/optim.py
- test/test_gromov.py
`relative_delta_cost_G` in `generic_conditional_gradient` is only computed when the cost != 0.
As the contract for cost evaluation in `generic_conditional_gradient` is rather generic, it could be the case it's set to 0. In this case computing `relative_delta_cost_G` fails because of zero division. As we only need the value of `relative_delta_cost_G` for early stopping condition, it doesn't hurt to skip the computation when cost is 0.
The code to reproduce the issue:
```python
import numpy as np
import ot
import ot.datasets
n_samples = 50
mu_s = np.array([0, 0])
cov_s = np.array([[1, 0], [0, 1]])
xs = ot.datasets.make_2D_samples_gauss(n_samples, mu_s, cov_s, random_state=4)
xt = xs[::-1].copy()
p = ot.unif(n_samples)
q = ot.unif(n_samples)
G0 = p[:, None] * q[None, :]
C1 = ot.dist(xs, xs) …
```
> [MRG] Gracefully handle cost = 0 in `generic_conditional_gradient`

- .gitignore
- RELEASES.md
- ot/backend.py
- ot/bregman.py
- test/test_backend.py
- test/test_bregman.py
The problem that the PR solves is that the `convolutional_barycenter2d` and `convolutional_barycenter2d` functions were not working on different devices (e.g. using PyTorch with CUDA). It was detected that the error came from the `linspace` method of the backends not having a `type_as` argument.
* Add a test in `test_backend.py` that checks if the `type_as` argument in the `linspace` method works.
* Add the tests `test_wasserstein_bary_2d_d_dtype_device`, `test_wasserstein_bary_2d_device_tf`, `test_wasserstein_bary_2d_debiased_dtype_device` and `test_wasserstein_bary_2d_debiased_device_tf` which mirror the `test_sinkhorn2_variants_dtype_device` and `test_sinkhorn2_variants_device_tf` tests to check if the barycenter work with different dtypes and devices.
> [MRG] Debug convolutional methods that compute barycenters to work with different devices.

- RELEASES.md
- ot/__init__.py
- ot/da.py
- ot/gromov/_bregman.py
- ot/gromov/_gw.py
- ot/gromov/_semirelaxed.py
- ot/optim.py
- ot/solvers.py
- ot/utils.py
- test/test_gromov.py
- test/test_solvers.py
- test/test_utils.py
in this PR I propose the implementation of the new API for Gromov-Wasserstsein solvers. Similarly to `ot.solve` we now have a function `ot.solve_gromov` that can be used as follows
```python
res = ot.solve_gromov(Ca, Cb) # uniform weights
res = ot.solve_gromov(Ca, Cb, a=a, b=b) # given weights
res = ot.solve_gromov(Ca, Cb, loss='KL') # uniform weights
res = ot.solve_gromov(Ca, Cb, M, alpha=0.5) # uniform weights
res = ot.solve_gromov(Ca, Cb, M, a=a, b=b, alpha=0.1) # given weights
res = ot.solve_gromov(Ca, Cb, reg=1) # GW
res = ot.solve_gromov(Ca, Cb, M, reg=1, alpha=0.5) # FGW
res=ot.solve_gromov(Ca, Cb, unbalanced_type='semirelaxed') # GW
res=ot.solve_gromov(Ca, Cb, M, unbalanced_type='semirelaxed') # FGW
res=ot.solve_gromov(Ca, Cb,unbalanced=0.8, unbalanced_type='partial') # partial GW …
```
> [MRG] New API for gromov solvers

- RELEASES.md
- examples/barycenters/plot_barycenter_lp_vs_entropic.py
- ot/lp/cvx.py
- requirements.txt
- setup.py
Scipy has since 1.6 new C++ LP solvers that can handle very well sparse matrices and lead to better solutions. 
This PR bump the scipy requirement and use now as default solver for LP barycenter the new "highs-ipm" solver that is more than 10 times faster on the example in the documentation
> [WIP] update LP barycenter with new scipy solvers

- RELEASES.md
- ot/unbalanced.py
- ot/utils.py
- test/test_unbalanced.py
- Modify all unbalanced solvers in `unbalanced.py ` (except for barycenter), so that the argument `reg_m` can take either a scalar, or an indexable object of length 1 or 2. 
- Edit `mm_unbalanced` method so that it can be used for both unregularized and regularized problems (previously supported unregularized only). Also, fix an implementation error of matrix $K$ in the $L_2$ case.
- Fix the KL formula and the corresponding gradient for L-BFGS-B solver.
- Add corresponding tests to `test_unbalanced.py`.
1. The current solvers for unbalanced OT have some limitations, which may restrict their usage in practice.
- The `sinkhorn_unbalanced` and `lbfgsb_unbalanced` methods only allow for `reg_m` to be a scalar, thus impose the same penalization on both marginals.
- The `mm_unbalanced` method …
> [MRG] Extend unbalanced OT solvers for more flexibility

- RELEASES.md
- ot/factored.py
- ot/utils.py
- test/test_factored.py
- test/test_utils.py
This PR adds a very simple LazyTensor class that can implement large scale matrices and tensors that are computed only lazily when getting slices of the tensor.
This class will be very interesting when implementing large scale OT problems such as factored OT, low rank OT and lazy implementation of sinkhorn. The objective is to be very simple with a storage of all necessary data and a function that compute the values on sliced (without computing the full tensor).
Exemple of use
```python
import numpy as np
from ot.utils import LazyTensor, 
n1=100
n2=200
x1 = np.random.randn(n1,2)
x2 = np.random.randn(n2,2)
def getitem(i,j, x1, x2):
return np.dot(x1[i], x2[j].T)
T = LazyTensor((n1,n2),getitem, x1=x1, x2=x2)
print(T.shape)
print(T)
full_T = T[:]
T11 = T[1,1]
T1 = T[1]
Tsliced = T[::10,5] …
```
> [MRG] Add LazyTensor for large scale OT

- RELEASES.md
- ot/gromov/_gw.py
- test/test_gromov.py
- Add exact line-search for `ot.gromov.gromov_wasserstein` and `ot.gromov.fused_gromov_wasserstein` when `loss_fun = 'kl_loss'` which can be called by setting `armijo=False`(default for the method). Note that these solvers ignored the provided `armijo` parameter with this loss enforcing `armijo=True`.
- Extend `ot.gromov.solve_gromov_linesearch` to any loss with common decomposition.
- Adapt the behavior of dependent solvers that also enforced `armijo=True`: `ot.gromov.gromov_barycenters` and `ot.gromov.fgw_barycenters`
- Add gradients in this setting for `ot.gromov.gromov_wasserstein2` and `ot.gromov.fused_gromov_wasserstein2`
- Extended existing test for `ot.gromov.gromov_wasserstein` and `ot.gromov.fused_gromov_wasserstein` with kl loss, looping over armijo values.
> [MRG] Add exact line-search for (f)gw solvers with kl_loss

- RELEASES.md
- ot/gromov/_semirelaxed.py
- ot/gromov/_utils.py
- test/test_gromov.py
- Add `loss_fun="kl_loss"` to all semi-relaxed (f)gw solvers.
- line-search for conditional gradient solvers `solve_semirelaxed_gromov_linesearch` now support any decomposable functions as for gromov-wasserstein : implied to add a parameter `fC2t` (which corresponds to $f_2(C_2)^\top$ in this [note](https://github.com/cedricvincentcuaz/cedricvincentcuaz.github.io/blob/master/POT/FGW___POT.pdf)). Previously existing parameters $C_1$ and $C_2$ should be past $h_1(C_1)$ and $h_2(C_2)$ as values - this is explained in the function documentation.
- Extended most existing tests for these functions by looping over admissible values of `loss_fun`.
> [MRG] add kl_loss to all semi-relaxed (f)gw solvers

- RELEASES.md
- Correct conflicts in RELEASES.md from previous merge in master.
> [MRG] fix conflict with RELEASES.md

- RELEASES.md
- ot/gromov/_gw.py
- test/test_gromov.py
- Add note for integer inputs in the documentation of :`gromov_wasserstein`, `gromov_wasserstein2`, `fused_gromov_wasserstein`, `fused_gromov_wasserstein2` 
- Add warnings for integer inputs in : `gromov_wasserstein`, `fused_gromov_wasserstein`
- Address issue #530 
- Add tests with integers in `test_gromov`: `test_gromov_integer_warnings`, `test_fgw_integer_warnings`
> [WIP] documentation and warnings in (f)gw cg solvers for integer inputs

- RELEASES.md
- ot/gromov/_gw.py
- test/test_gromov.py
- correct independence of fgw barycenters to init by changing performing the 1st barycenter update after the computing the 1st OT matrices.
- Removed some unnecessary operations when `fixed_features=True` and/or `warmstart=False`.
- Cf Issue #547 
- already handled by existing tests.
> [MRG] correct independence of fgw barycenters to init

- RELEASES.md
- ot/backend.py
- test/test_gaussian.py
Fix previously added (see PR #507) precision change when computing norm on the PyTorch backend.
Precision change is not necessary, and fails on devices which don't have support for double precision.
Related discussion #570.
n/a
> [MRG] Avoid changing precision in the backend

- RELEASES.md
- ot/gromov/_bregman.py
- ot/gromov/_gw.py
- test/test_gromov.py
- add a new option to (un)regularized (f)gw barycenter solvers : `conv_criterion` taking values into `{"barycenter", "loss"}` so the user can choose convergence criterions either based on the absolute norm variations of the barycenter, or relative loss variations, respectively : The last criterion is most likely meaningful for most applications, plus suit to the ones used in inner (f)gw solvers based on conditional gradient. This feature is also added to the entropic (f)gw barycenter solvers and would come with an overhead of computing the loss at the last iteration of the inner entropic solvers. Whereas for CG inner functions, computing the barycenter loss is performed in O(#samples). 
- Trying to harmonise the behavior across all (f)gw barycenter solvers :
- Some solvers were updating …
> [MRG] (f)gw barycenter solvers new features and cleaning

- README.md
- ot/gromov/_semirelaxed.py
Forgot to put the paper citation for sr(f)gw conditional gradient solvers with `kl_loss`.
- [] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.
> [MRG] add citation for sr(f)gw-kl

- RELEASES.md
- ot/gaussian.py
- test/test_gaussian.py
This PR introduces a function to compute Bures-Wasserstein Barycenter
I chek my code with the closed form for diagonal covariance, which has a closed form.
> [MRG] Add Wasserstein barycenter for Gaussian distribution

- RELEASES.md
- examples/barycenters/plot_gaussian_barycenter.py
- ot/gaussian.py
> [MRG] Add Bures-Wasserstein arycenetrs example (and debug the solver)

- RELEASES.md
- ot/da.py
- test/test_da.py
Cost correction for mismatched labels in `ot.da.BaseTransport` fit is fixed. The original change was introduced in the #587. 
Previous version of the procedure was failing when `limit_max` is set to `Inf`, resulting in `self.cost_` having NANs.
Additional checks in the DA tests to ensure that cost does not contain NANs.
> Fix DA cost correction when cost limit is set to Inf

- ot/backend.py
- ot/solvers.py
- test/test_backend.py
- test/test_solvers.py
This PR aims at 
This PR should solve #565 and greatly limit memory for sinkhorn when computing gradienst wrt the value.
In order to use implicit diffeerntiation one needs to set the `grad` parameter in `ot.solve`and `ot.solve_sample`as such
```python
sol = ot.solve(M, a, b, reg=10, grad='implicit')
sol.value.backward()
```
On a simple example with pytorch arrays with required gradients, I has a 1000x gain in memory for solving the problem when a  large number of sinkhorn operations are needed.
> [MRG] Add implicit Sinkhorn gradients

- requirements.txt
Limit the max version of jax to allow for old config because of pymanopt using deprecated version
> [MRG] Temporary limit on jax version

- RELEASES.md
- ot/__init__.py
- ot/gromov/_gw.py
- ot/gromov/_semirelaxed.py
- ot/lp/__init__.py
- ot/lp/solver_1d.py
- ot/optim.py
- ot/utils.py
- test/conftest.py
- test/test_ot.py
- test/test_utils.py
> [MRG] Fix bug in emd2 with empty weighs on backends

- RELEASES.md
- ot/gromov/_gw.py
Correct a sign error of the nx.set_gradient for gromov (and fused gromov) when loss_fun = 'kl_loss'.
The correct formula is:
gC2 = - nx.dot(T.T, nx.dot(C1, T)) / (C2 + 1e-15) + nx.outer(q, q)
instead of 
gC2 =  nx.dot(T.T, nx.dot(C1, T)) / (C2 + 1e-15) + nx.outer(q, q)
You can run this code:
```
from ot import gromov_wasserstein2,unif
import torch 
C1 = torch.rand((2,2), requires_grad = False)
C2 = 1 - C1
C2.requires_grad = True
eta = 1e-1
for step in range(100):
loss = gromov_wasserstein2(C1=C1,C2=C2,p=unif(2,type_as=C2),q=unif(2,type_as=C2),loss_fun='square_loss')
grad = torch.autograd.grad(loss, C2)[0]
C2 = C2 - eta*grad
C2 = torch.clip(C2,0,1)
print(loss)
````
You will see that the gradient descent diverges. It converges when we fix the sign error.
> fix the sign of gradient for kl gromov

- RELEASES.md
- ot/gromov/_semirelaxed.py
Fix same issue than in PR #610 for sr(F)GW.
> [MRG] fix grad sign sr(F)GW with KL loss

- RELEASES.md
- examples/plot_solve_variants.py
- ot/__init__.py
- ot/solvers.py
- ot/unbalanced.py
- test/test_solvers.py
In this PR we propose the following contribution
- generalization of Unbalaced BFGS solver to TV marginal penalization and general regularizer terms (given as a tuple of value, grad functions)
- Generalization of ot.solve to handle TV marginal penalization for unbalanced solver and general regularization for unbalanced and exact ot solver (using cg)
- Example of a grid of regularization and marginal penalization in the doc
> [MRG] More general solvers for ``ot.solve`and examples of different variants.

- RELEASES.md
- ot/da.py
- ot/regpath.py
- pyproject.toml
- setup.py
Resolves https://github.com/PythonOT/POT/issues/626.
* Add `numpy>=2.0.0` to `build-system` `requires` to build NumPy `1.x` and `2.x` compatible
wheels.
- c.f. https://numpy.org/doc/stable/dev/depending_on_numpy.html#numpy-2-0-specific-advice
- As NumPy 2.0 is Python 3.9+, also need to conditionally support `oldest-supported-numpy` for Python 3.8.
* Remove `wheel` from `build-system` `requires` as it is never required and injected automatically by `setuptools` only when needed.
- c.f. https://learn.scientific-python.org/development/guides/packaging-classic/
* Remove `setup_requires` metadata from `setup.py` as it is deprecated and should defer to PEP 517/518.
- c.f. https://learn.scientific-python.org/development/guides/packaging-classic/#pep-517518-support-high-priority
* Use `np.inf` to …
> [BLD] Add support for NumPy 2.0 wheels

- .github/workflows/build_wheels_weekly.yml
- Makefile
The build system should define all required build components and make them available at wheel build time. As this `pip` install step is not required, remove `CIBW_BEFORE_BUILD`.
From the `cibuildwheel` docs https://cibuildwheel.pypa.io/en/stable/options/#before-build
> If dependencies are required to build your wheel (for example if you include a header from a Python module), instead of using this command, we recommend adding requirements to a pyproject.toml file's build-system.requires array instead.
Follow up PR to PR #629 
- [N/A] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.
> [CI] Remove redundant CIBW_BEFORE_BUILD

- setup.py
* Compliment to PR https://github.com/PythonOT/POT/pull/629.
* Update `requires-python` metadata through `setuptools`'s `python_requires` to reflect that only Python 3.7+ is distributed on PyPI and only Python 3.8+ is tested in CI and so Python 3.6 is not supported.
- c.f. https://peps.python.org/pep-0621/#requires-python
- The use of `requires-python` is to provide guards to keep older CPython versions from installing releases that could contain unrunnable code.
* Python 3.6 is also EOL
```
┌───────┬────────────┬─────────┬────────────────┬────────────┬────────────┐
│ cycle │  release   │ latest  │ latest release │  support   │    eol     │
├───────┼────────────┼─────────┼────────────────┼────────────┼────────────┤
│ 3.12  │ 2023-10-02 │ 3.12.4  │   2024-06-06   │ 2025-04-02 │ 2028-10-31 …
```
> [BLD] Update requires-python metadata to Python 3.7

- .github/workflows/build_tests.yml
* Use the 'macos-latest' runs-on option which now defaults to 'macos-14' which are Apple silicon runners.
- c.f. https://github.com/actions/runner-images/blob/d31241d2c8c646cd0ba18579836636e62c38f1c9/images/macos/macos-14-arm64-Readme.md
* Keep a 'macos-13' runner to continue to test x86 based macOS for the latest Python version.
- c.f. https://github.com/actions/runner-images/blob/d31241d2c8c646cd0ba18579836636e62c38f1c9/images/macos/macos-13-Readme.md
x86 macOS should still be tested.
- [N/A] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.
> [CI] Add x86 based macOS to testing

- RELEASES.md
- ot/optim.py
> [Fix] import linesearch for modern scipy

- .github/workflows/build_tests.yml
- requirements_all.txt
- setup.py
* Add Python 3.12 to the Linux test matrix.
* Use Python 3.12 as the default Python for all other CI tests.
- [N/A] I have added the PR and Issue fix to the [**RELEASES.md**](RELEASES.md) file.
> [CI] Use Python 3.12 as default for tests

- RELEASES.md
- ot/backend.py
- requirements_all.txt
> [WIP] Upgrade JAX support from 0.4.24 to 0.4.30

- ot/optim.py
As most users will be installing the latest `scipy` release when they install `POT`, default to using the `scipy` `v1.8.0+` API and catch the `ModuleNotFoundError` in the rare case in which `scipy` `v1.7.3` or older is required. (https://github.com/scipy/scipy/pull/14966 is in `scipy` `v1.8.0+`)
In all situations,import from the `scipy.optimize.{_}linesearch` API as the newest version of scipy that supports Python 3.7 is `v1.7.3` which does not support `from scipy.optimize import scalar_search_armijo`, just as scipy v1.14.0+ does not.
Amends PR https://github.com/PythonOT/POT/pull/642
```console
$ docker run --rm -ti python:3.8 /bin/bash
root@62c4a7db4ec9:/# python -m pip --quiet install uv
root@62c4a7db4ec9:/# uv venv
Using Python 3.8.19 interpreter at: usr/local/bin/python3
Creating …
```
> [FIX] Default to using scipy v1.8.0+ API

- RELEASES.md
- ot/backend.py
- ot/bregman/_barycenter.py
- ot/coot.py
- ot/gromov/_utils.py
- ot/partial.py
- test/test_utils.py
- Add feature `mass=False|True` in `nx.kl_div` to compute the generalized kl divergence either with the difference of total masses or not.
- Screened the toolbox to ensure proper use of `nx.kl_div` and along the way i set all existing offsets to nx.log to 1e-16.
> [WIP] add mass feature to nx.kl_div and harmonize kl computation in the toolbox

- ot/gnn/_layers.py
- ot/gromov/_quantized.py
Some instances of docstrings using TeX were incorrectly specified as ordinary strings, leading to the TeX macros being interpreted as escape sequences.
> Use raw strings with TeX

- RELEASES.md
- ot/lp/emd_wrap.pyx
- ot/lp/solver_1d.py
- test/test_1d_solver.py
The point here is to prevent anyone from using the `emd_1d` and `emd2_1d` functions with metrics that are not Minkowski ones, since this implementation is valid only in this case.
As such, I have left the opportunity to use `'sqeuclidean'`, `'minkowski'`, `'cityblock'`,  or `'euclidean'` as metrics. Another option would be to remove the `metrics` keyword and only specify `p`, but that would break backward compatibility, so I assumed this change was better for maintenance purposes. Let me know if this should be changed.
This PR aims at solving issue #669.
Not tested yet.
> [MRG] Only Minkowski metrics can be used for emd_1d

- README.md
- RELEASES.md
- examples/unbalanced-partial/plot_conv_sinkhorn_ti.py
- ot/backend.py
- ot/unbalanced/__init__.py
- ot/unbalanced/_sinkhorn.py
- test/unbalanced/test_sinkhorn.py
This PR aims to add the Translation Invariant Sinkhorn algorithm proposed in [Faster Unbalanced Optimal Transport: Translation invariant Sinkhorn and 1-D Frank-Wolfe
](https://proceedings.mlr.press/v151/sejourne22a.html) to solve the Unbalanced OT problem. 
- Added the function `sinkhorn_unbalanced_translation_invariant`  in `unbalanced/_sinkhorn.py`
- Added an example in `plot_conv_sinkhorn_ti.py` to demonstrate the convergence benefits
- Added the method in `unbalanced/test_sinkhorn.py`
This version of Sinkhorn converges faster than the classical Sinkhorn algorithm for UOT.
The function can be called by using the method "sinkhorn_translation_invariant" in `sinkhorn_unbalanced`, so I added this method in the itertools of tests of `unbalanced/test_sinkhorn.py`.
> [MRG] Translation Invariant Sinkhorn for Unbalanced OT

- .github/workflows/build_doc.yml
- .github/workflows/build_wheels.yml
- .github/workflows/build_wheels_weekly.yml
* actions/upload-artifact v3 will be deprecated as of 2024-12-05 and will result in workflow failures afterwards.
* Use unique names to avoid overwrite.
I received this email from GitHub which applies to POT:
> Artifact actions v3 will be deprecated by December 5, 2024. You are receiving this email because you have GitHub Actions workflows using v3 of [actions/upload-artifact](https://github.com/actions/upload-artifact) or [actions/download-artifact](https://github.com/actions/download-artifact). After this date using v3 of these actions will result in a workflow failure. Artifacts within their retention period will remain accessible from the UI or REST API regardless of the version used to upload.
> 
> To raise awareness of the upcoming removal, we will temporarily fail jobs using v3 of …
> [CI] Update actions/upload-artifact to v4

- RELEASES.md
- ot/mapping.py
CVXPY changed its default solver (from ECOS to Clarabel), changing the mapping solvers to use the default CVXPY solver instead of asking for an old solver that is no longer installed by default
Fix #688
Example + pytest
> [MRG] no longer impose ECOS solver for SSNB, use new CVXPY default (Clarabel)

- CONTRIBUTORS.md
- RELEASES.md
- ot/__init__.py
- ot/backend.py
- ot/gmm.py
- test/test_backend.py
This PR fixes numerical instability issues in `ot.gmm` in the `gaussian_pdf`and `gmm_ot_apply_map` methods, arising when handling high-dimensional Gaussians (see #689).
> [FIX] numerical errors in ot.gmm

- RELEASES.md
- examples/backends/plot_Sinkhorn_gradients.py
- examples/plot_Sinkhorn_gradients.py
- ot/solvers.py
- test/test_solvers.py
I added a `grad=last_step` feature to the `ot.solvers.solve` function to limit the gradient computation to the last iteration of Sinkhorn instead of computing the gradient for every iteration.
This change is required in the case where computing the gradient for all the Sinkhorn iterations is too heavy.
I created a `test_solve_last_step` test to check that the gradient is different when using `grad=last_step` and `grad=autodiff`.
> [MRG] Sinkhorn gradient last step

- RELEASES.md
- docs/source/_templates/versions.html
- docs/source/conf.py
This PR adds the version number in the documentation since it was removed because of the update of rtd theme.
We now have this:
> [Fix] Add version number back to the doc

- RELEASES.md
- ot/unbalanced/_sinkhorn.py
Issue #691 has highlighted a change in default behavior for the regularization of unbalanced OT. This was not properly stated in the release note but we added here a warning block in the doc of the functions to make teh change in behavior more clear.
> [DOC] Update doc for unbalanced sinkhorn 

- RELEASES.md
- ot/bregman/_convolutional.py
- test/test_bregman.py
Refactor the `ot.bregman._convolutional.py` module to improve the readability of the module. These includes:
- Add a function that returns `convol_img` function.
- Leave the warning message as a constant in the top of the module.
- Create a function for the verbose report.
There is a lot of duplicate code in this module, which can be encapsulated in functions to make it more modular.
> [MRG] Refactor: improve readibility in the convolutional module

- RELEASES.md
- ot/gaussian.py
* Add backslash in mathematical environment. 
E.g.: from 
```
:math:`\left{\mathcal{N}(\mu,\Sigma)\right}_{i=1}^n`
```
now is 
```
:math:`\left\{\mathcal{N}(\mu,\Sigma)\right\}_{i=1}^n`
```
* Delete spaces at the change of line.
In the documentation of [`ot.gaussian`](https://pythonot.github.io/master/gen_modules/ot.gaussian.html) appears the following warning:
`Missing or unrecognized delimiter for \left`
> [MRG] docs: fix missing delimeter for left

- RELEASES.md
- ot/bregman/_barycenter.py
- ot/bregman/_sinkhorn.py
- ot/da.py
- ot/dr.py
- ot/gaussian.py
- ot/gromov/_gw.py
- ot/gromov/_partial.py
- ot/gromov/_semirelaxed.py
- ot/gromov/_utils.py
- ot/lp/_barycenter_solvers.py
- ot/mapping.py
- ot/optim.py
- ot/partial.py
- ot/smooth.py
- ot/stochastic.py
- ot/unbalanced/_mm.py
- ot/unbalanced/_sinkhorn.py
- ot/weak.py
Correct references rendering in documentation.
No code modification.
There are many mistakes in the current documentation https://pythonot.github.io/
> Clean references in documentation

- RELEASES.md
- ot/gaussian.py
- ot/unbalanced/_lbfgs.py
This is to avoid the following warning:
```
SyntaxWarning: invalid escape sequence '\m'
```
Add a `r` at the beggining of the `_get_loss_unbalanced` documentation
When I update the library, I realised that throws the following warning:
```
/home/.../site-packages/ot/unbalanced/_lbfgs.py:21: SyntaxWarning: invalid escape sequence '\m'
"""
```
> [MRG] fix: make the documentation of _get_loss_unbalanced as a raw string

- RELEASES.md
- docs/source/conf.py
- docs/source/index.rst
- docs/source/user_guide.rst
- examples/plot_OT_2D_samples.py
- examples/plot_quickstart_guide.py
- ot/bregman/_empirical.py
- ot/lp/__init__.py
- test/test_bregman.py
> [MRG] New Quickstart guide and revamp User guide

- RELEASES.md
- ot/gromov/_gw.py
In `ot.gromov`, I  propose minor changes in the docstring:
- Changing "conjugate gradient" to "conditional gradient"
- Making the mathematical notation consistent in `gromov_wasserstein` and `gromov_wasserstein2` by changing from `\gamma` to `T` for the transportation plan in the constraints. 
Thank you for your consideration!
> [DOC] Minor suggestions for the Gromov Wasserstein docstring

- .github/workflows/build_tests.yml
- .github/workflows/build_wheels.yml
- .github/workflows/build_wheels_weekly.yml
- RELEASES.md
Debugging the wheels build by removing old versions of python.
> [MRG] Debug wheels building

- RELEASES.md
- ot/utils.py
This is a version of PR #734  with release file completed and doc updated
> Finish PR 734 : typo in \text{max_nz} in ot.utils.projection_sparse_simplex

- MANIFEST.in
- RELEASES.md
- ot/__init__.py
> Fix Manifest and change numbering for post release

- README.md
- RELEASES.md
- examples/sliced-wasserstein/plot_sliced_plans.py
- ot/__init__.py
- ot/sliced.py
- test/test_sliced.py
Implements min-Pivot Sliced Plans [Mahey et al.](https://proceedings.neurips.cc/paper_files/paper/2023/hash/6f1346bac8b02f76a631400e2799b24b-Abstract-Conference.html), [Tanguy et al.](https://arxiv.org/abs/2508.01243) and Expected Sliced Plans [Liu et al.](https://openreview.net/forum?id=P7O1Vt1BdU), [Tanguy et al.](https://arxiv.org/abs/2508.01243), and Generalised Sliced Wasserstein Plans [Chapel et al.](https://arxiv.org/abs/2505.22049).
Checklist:
> [WIP] Sliced OT Plans
